/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoldSetting: typeof import('./src/components/materials/BoldSetting.vue')['default']
    ButtonSelection: typeof import('./src/components/ButtonSelection.vue')['default']
    CenterSetting: typeof import('./src/components/materials/CenterSetting.vue')['default']
    ColorSetting: typeof import('./src/components/materials/ColorSetting.vue')['default']
    DropdownChoice: typeof import('./src/components/buttonItem/DropdownChoice.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ImageSingleChoice: typeof import('./src/components/buttonItem/ImageSingleChoice.vue')['default']
    ItalicSetting: typeof import('./src/components/materials/ItalicSetting.vue')['default']
    MultipleChoice: typeof import('./src/components/buttonItem/MultipleChoice.vue')['default']
    RadioOption: typeof import('./src/components/materials/RadioOption.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleChoice: typeof import('./src/components/buttonItem/SingleChoice.vue')['default']
    SizeSetting: typeof import('./src/components/materials/SizeSetting.vue')['default']
  }
}
