/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoldSetting: typeof import('./src/components/editor/BoldSetting.vue')['default']
    ButtonSelection: typeof import('./src/components/ButtonSelection.vue')['default']
    CenterSetting: typeof import('./src/components/editor/CenterSetting.vue')['default']
    ColorSetting: typeof import('./src/components/editor/ColorSetting.vue')['default']
    DateComponent: typeof import('./src/components/advanced/DateComponent.vue')['default']
    DropdownChoice: typeof import('./src/components/choice/DropdownChoice.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ImageSingleChoice: typeof import('./src/components/choice/ImageSingleChoice.vue')['default']
    ItalicSetting: typeof import('./src/components/editor/ItalicSetting.vue')['default']
    MultipleChoice: typeof import('./src/components/choice/MultipleChoice.vue')['default']
    RadioOption: typeof import('./src/components/editor/RadioOption.vue')['default']
    RateComponent: typeof import('./src/components/advanced/RateComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleChoice: typeof import('./src/components/choice/SingleChoice.vue')['default']
    SizeSetting: typeof import('./src/components/editor/SizeSetting.vue')['default']
  }
}
